apiVersion: v1
kind: Namespace
metadata:
  name: scraper
  labels:
    name: scraper
    environment: production
    app.kubernetes.io/name: scraper
    app.kubernetes.io/part-of: documentation-scraper
    app.kubernetes.io/managed-by: kubectl

---
# Resource Quota for namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: scraper-quota
  namespace: scraper
spec:
  hard:
    requests.cpu: "50"
    requests.memory: "100Gi"
    limits.cpu: "100"
    limits.memory: "200Gi"
    persistentvolumeclaims: "20"
    services.loadbalancers: "2"
    count/deployments.apps: "10"
    count/services: "10"

---
# Limit Range for pods
apiVersion: v1
kind: LimitRange
metadata:
  name: scraper-limitrange
  namespace: scraper
spec:
  limits:
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container

  - max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "200m"
      memory: "256Mi"
    type: Pod

---
# Network Policy: Allow internal traffic only
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scraper-network-policy
  namespace: scraper
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

  ingress:
  # Allow from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000

  # Allow internal traffic
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 8000  # API
    - protocol: TCP
      port: 9090  # Metrics

  egress:
  # Allow DNS
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53

  # Allow internal traffic
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 6379
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 8000

  # Allow external HTTPS (for scraping)
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
